export type PhetSubject = "math" | "physics" | "chemistry" | "biology" | "earth-science"

export interface PhetSim {
  id: string
  name_en: string
  name_zh: string
  subject: PhetSubject
  topics: string[]
  grade_range: [number, number]
  description_zh: string
  url_zh: string
  url_en: string
  thumbnail: string
  difficulty: 1 | 2 | 3
  interactive_elements: string[]
  learning_goals: string[]
  duration_minutes: number
}

function phetUrl(id: string, locale: "zh_CN" | "en") {
  return `https://phet.colorado.edu/sims/html/${id}/latest/${id}_${locale}.html`
}

function phetThumbnail(id: string) {
  return `https://phet.colorado.edu/sims/html/${id}/latest/${id}-600.png`
}

function sim(input: Omit<PhetSim, "url_zh" | "url_en" | "thumbnail">): PhetSim {
  return {
    ...input,
    url_zh: phetUrl(input.id, "zh_CN"),
    url_en: phetUrl(input.id, "en"),
    thumbnail: phetThumbnail(input.id),
  }
}

export const PHET_SIMS: PhetSim[] = [
  sim({
    id: "graphing-quadratics",
    name_en: "Graphing Quadratics",
    name_zh: "二次函数图像",
    subject: "math",
    topics: ["二次函数", "抛物线", "顶点", "对称轴"],
    grade_range: [8, 11],
    description_zh: "通过拖动参数观察抛物线开口、顶点和对称轴的变化，帮助学生把二次函数公式与图像特征建立联系。",
    difficulty: 2,
    interactive_elements: ["调节二次项系数", "移动顶点", "观察对称轴"],
    learning_goals: ["理解二次函数参数含义", "识别顶点和对称轴", "解释图像平移与伸缩"],
    duration_minutes: 18,
  }),
  sim({
    id: "graphing-lines",
    name_en: "Graphing Lines",
    name_zh: "一次函数图像",
    subject: "math",
    topics: ["一次函数", "斜率", "截距", "线性方程"],
    grade_range: [7, 9],
    description_zh: "用斜率和截距控制直线，直观看到线性方程中每个参数如何改变图像的位置与倾斜程度。",
    difficulty: 1,
    interactive_elements: ["拖拽直线", "调节斜率", "调节截距"],
    learning_goals: ["读懂斜率和截距", "连接方程与图像", "比较不同直线变化"],
    duration_minutes: 15,
  }),
  sim({
    id: "graphing-slope-intercept",
    name_en: "Graphing Slope-Intercept",
    name_zh: "斜截式",
    subject: "math",
    topics: ["斜率", "y轴截距", "直线方程"],
    grade_range: [7, 9],
    description_zh: "围绕 y=mx+b 的结构探索斜率和截距，让学生通过操作建立斜截式的图像直觉。",
    difficulty: 1,
    interactive_elements: ["滑块调节斜率", "滑块调节截距", "显示方程"],
    learning_goals: ["掌握斜截式", "解释 m 与 b 的作用", "根据图像写方程"],
    duration_minutes: 15,
  }),
  sim({
    id: "function-builder",
    name_en: "Function Builder",
    name_zh: "函数机器",
    subject: "math",
    topics: ["函数概念", "输入输出", "函数组合"],
    grade_range: [6, 8],
    description_zh: "像搭积木一样组合函数规则，观察输入经过多步变换后的输出，适合建立函数机器的核心概念。",
    difficulty: 2,
    interactive_elements: ["拖拽函数模块", "输入数值", "组合变换"],
    learning_goals: ["理解输入输出关系", "描述函数规则", "体验函数组合"],
    duration_minutes: 18,
  }),
  sim({
    id: "function-builder-basics",
    name_en: "Function Builder Basics",
    name_zh: "函数机器基础",
    subject: "math",
    topics: ["函数入门", "规律发现"],
    grade_range: [5, 7],
    description_zh: "从简单规则开始探索输入和输出的对应关系，帮助低年级学生用实验方式发现函数规律。",
    difficulty: 1,
    interactive_elements: ["选择规则", "测试输入", "猜测输出"],
    learning_goals: ["发现数量规律", "理解变量对应", "用语言描述规则"],
    duration_minutes: 12,
  }),
  sim({
    id: "calculus-grapher",
    name_en: "Calculus Grapher",
    name_zh: "微积分画板",
    subject: "math",
    topics: ["导数", "积分", "函数图像", "变化率"],
    grade_range: [10, 12],
    description_zh: "同时观察函数、导数和积分图像，帮助高中学生把变化率、面积累积与曲线形状联系起来。",
    difficulty: 3,
    interactive_elements: ["绘制函数", "显示导数", "显示积分"],
    learning_goals: ["理解导数图像含义", "认识积分累积", "比较函数与变化率"],
    duration_minutes: 22,
  }),
  sim({
    id: "curve-fitting",
    name_en: "Curve Fitting",
    name_zh: "曲线拟合",
    subject: "math",
    topics: ["数据拟合", "线性回归", "最小二乘法"],
    grade_range: [9, 12],
    description_zh: "拖拽数据点并拟合直线或曲线，体验模型如何描述数据趋势以及误差对拟合结果的影响。",
    difficulty: 3,
    interactive_elements: ["拖拽数据点", "选择拟合模型", "观察误差"],
    learning_goals: ["理解数据趋势", "比较拟合质量", "认识回归思想"],
    duration_minutes: 20,
  }),
  sim({
    id: "equation-grapher",
    name_en: "Equation Grapher",
    name_zh: "方程画图器",
    subject: "math",
    topics: ["多项式", "系数", "图像变换"],
    grade_range: [8, 11],
    description_zh: "输入或调节方程参数，实时观察函数图像变化，适合用于多项式和图像变换的探究课。",
    difficulty: 2,
    interactive_elements: ["编辑方程", "调节系数", "缩放坐标"],
    learning_goals: ["连接代数式与图像", "解释系数影响", "观察图像变换"],
    duration_minutes: 18,
  }),
  sim({
    id: "trig-tour",
    name_en: "Trig Tour",
    name_zh: "三角函数之旅",
    subject: "math",
    topics: ["正弦", "余弦", "正切", "单位圆"],
    grade_range: [9, 11],
    description_zh: "借助单位圆和函数图像同步变化，理解角度、坐标和三角函数值之间的动态关系。",
    difficulty: 2,
    interactive_elements: ["旋转角度", "查看单位圆", "同步函数图像"],
    learning_goals: ["理解单位圆定义", "比较正弦余弦", "解释周期变化"],
    duration_minutes: 18,
  }),
  sim({
    id: "unit-rates",
    name_en: "Unit Rates",
    name_zh: "单位费率",
    subject: "math",
    topics: ["比例", "速率", "单位换算"],
    grade_range: [5, 7],
    description_zh: "通过生活化场景比较单位费率，让学生在操作中理解比例、速率和单位换算的实际意义。",
    difficulty: 1,
    interactive_elements: ["比较价格", "调整数量", "查看单位率"],
    learning_goals: ["计算单位率", "比较比例关系", "解释生活问题"],
    duration_minutes: 12,
  }),
  sim({
    id: "area-builder",
    name_en: "Area Builder",
    name_zh: "面积建造者",
    subject: "math",
    topics: ["面积", "周长", "矩形", "组合图形"],
    grade_range: [4, 6],
    description_zh: "拖拽小方块搭建图形，观察面积与周长如何变化，适合建立面积单位和组合图形意识。",
    difficulty: 1,
    interactive_elements: ["拖拽方块", "搭建矩形", "显示面积周长"],
    learning_goals: ["理解面积单位", "区分面积与周长", "拆分组合图形"],
    duration_minutes: 12,
  }),
  sim({
    id: "fraction-matcher",
    name_en: "Fraction Matcher",
    name_zh: "分数匹配",
    subject: "math",
    topics: ["分数", "等价分数", "分数比较"],
    grade_range: [4, 6],
    description_zh: "用图形、数轴和符号匹配分数，帮助学生理解等价分数以及不同表示之间的转换。",
    difficulty: 1,
    interactive_elements: ["匹配卡片", "比较图形", "查看分数表示"],
    learning_goals: ["识别等价分数", "比较分数大小", "转换多种表示"],
    duration_minutes: 12,
  }),
  sim({
    id: "make-a-ten",
    name_en: "Make a Ten",
    name_zh: "凑十法",
    subject: "math",
    topics: ["加法", "凑十", "口算"],
    grade_range: [1, 3],
    description_zh: "通过可视化操作练习凑十策略，让低年级学生把抽象加法拆成更容易心算的步骤。",
    difficulty: 1,
    interactive_elements: ["移动数字", "组合十", "即时反馈"],
    learning_goals: ["掌握凑十策略", "提升口算速度", "理解加法分解"],
    duration_minutes: 10,
  }),
  sim({
    id: "number-line-integers",
    name_en: "Number Line: Integers",
    name_zh: "数轴整数",
    subject: "math",
    topics: ["正负数", "数轴", "绝对值"],
    grade_range: [6, 7],
    description_zh: "在数轴上移动和比较整数，直观理解正负数的位置关系、距离和绝对值含义。",
    difficulty: 1,
    interactive_elements: ["拖动点", "比较整数", "观察距离"],
    learning_goals: ["认识正负数", "读懂数轴", "理解绝对值"],
    duration_minutes: 12,
  }),
  sim({
    id: "proportion-playground",
    name_en: "Proportion Playground",
    name_zh: "比例游乐场",
    subject: "math",
    topics: ["比例", "等比", "缩放"],
    grade_range: [6, 8],
    description_zh: "通过缩放和配比活动探索比例关系，帮助学生理解等比变化在图形和数量中的表现。",
    difficulty: 2,
    interactive_elements: ["缩放图形", "调节比例", "比较结果"],
    learning_goals: ["理解比例不变量", "应用等比缩放", "解释相似关系"],
    duration_minutes: 15,
  }),
  sim({
    id: "forces-and-motion-basics",
    name_en: "Forces and Motion: Basics",
    name_zh: "力和运动基础",
    subject: "physics",
    topics: ["力", "摩擦力", "牛顿定律", "加速度"],
    grade_range: [7, 9],
    description_zh: "推动物体并调节摩擦，观察合力、速度和加速度的关系，是入门牛顿运动定律的经典实验。",
    difficulty: 1,
    interactive_elements: ["施加推力", "调节摩擦", "观察速度"],
    learning_goals: ["理解力改变运动", "认识摩擦影响", "连接合力与加速度"],
    duration_minutes: 18,
  }),
  sim({
    id: "gravity-and-orbits",
    name_en: "Gravity and Orbits",
    name_zh: "万有引力与轨道",
    subject: "physics",
    topics: ["引力", "行星运动", "开普勒定律"],
    grade_range: [9, 11],
    description_zh: "调整天体质量和速度，观察轨道如何形成与改变，帮助学生理解引力和行星运动模型。",
    difficulty: 3,
    interactive_elements: ["调节质量", "改变速度", "观察轨道"],
    learning_goals: ["理解引力作用", "解释轨道运动", "认识开普勒规律"],
    duration_minutes: 22,
  }),
  sim({
    id: "energy-skate-park-basics",
    name_en: "Energy Skate Park: Basics",
    name_zh: "能量滑板公园",
    subject: "physics",
    topics: ["动能", "势能", "能量守恒"],
    grade_range: [8, 10],
    description_zh: "让滑板者在轨道上运动，实时观察动能、势能和热能变化，建立能量守恒的动态图像。",
    difficulty: 2,
    interactive_elements: ["拖拽轨道", "改变高度", "查看能量条"],
    learning_goals: ["区分动能势能", "理解能量转化", "解释能量守恒"],
    duration_minutes: 18,
  }),
  sim({
    id: "projectile-motion",
    name_en: "Projectile Motion",
    name_zh: "抛体运动",
    subject: "physics",
    topics: ["平抛", "斜抛", "初速度", "角度"],
    grade_range: [9, 11],
    description_zh: "改变发射角度、初速度和高度，观察抛物轨迹，适合分析水平和竖直方向运动分解。",
    difficulty: 2,
    interactive_elements: ["调节角度", "调节初速度", "显示轨迹"],
    learning_goals: ["分解抛体运动", "比较射程因素", "解释轨迹形状"],
    duration_minutes: 18,
  }),
  sim({
    id: "circuit-construction-kit-dc",
    name_en: "Circuit Construction Kit: DC",
    name_zh: "直流电路",
    subject: "physics",
    topics: ["电路", "电阻", "电流", "电压", "欧姆定律"],
    grade_range: [8, 10],
    description_zh: "像真实实验一样连接电池、导线和电阻，测量电流电压，适合安全地探索直流电路规律。",
    difficulty: 2,
    interactive_elements: ["搭建电路", "连接电表", "更换元件"],
    learning_goals: ["理解闭合电路", "测量电流电压", "应用欧姆定律"],
    duration_minutes: 22,
  }),
  sim({
    id: "wave-on-a-string",
    name_en: "Wave on a String",
    name_zh: "绳上的波",
    subject: "physics",
    topics: ["横波", "振幅", "频率", "波长"],
    grade_range: [9, 11],
    description_zh: "在绳子上产生脉冲或连续波，调节振幅、频率和张力，观察波的传播与反射。",
    difficulty: 2,
    interactive_elements: ["摇动绳端", "调节频率", "观察反射"],
    learning_goals: ["认识横波特征", "区分振幅频率波长", "解释反射现象"],
    duration_minutes: 18,
  }),
  sim({
    id: "pendulum-lab",
    name_en: "Pendulum Lab",
    name_zh: "钟摆实验室",
    subject: "physics",
    topics: ["单摆", "周期", "重力加速度"],
    grade_range: [9, 11],
    description_zh: "改变摆长、质量、角度和重力环境，测量周期变化，探索影响单摆周期的关键因素。",
    difficulty: 2,
    interactive_elements: ["调节摆长", "改变重力", "计时测量"],
    learning_goals: ["测量单摆周期", "判断影响因素", "理解简谐近似"],
    duration_minutes: 18,
  }),
  sim({
    id: "hookes-law",
    name_en: "Hooke's Law",
    name_zh: "胡克定律",
    subject: "physics",
    topics: ["弹簧", "弹力", "形变", "弹性系数"],
    grade_range: [8, 10],
    description_zh: "挂上不同重物并观察弹簧伸长，建立弹力与形变量成正比的实验认识。",
    difficulty: 1,
    interactive_elements: ["悬挂重物", "调节弹簧", "读取伸长量"],
    learning_goals: ["理解弹力方向", "认识劲度系数", "应用胡克定律"],
    duration_minutes: 15,
  }),
  sim({
    id: "ohms-law",
    name_en: "Ohm's Law",
    name_zh: "欧姆定律",
    subject: "physics",
    topics: ["电压", "电流", "电阻", "欧姆定律"],
    grade_range: [8, 10],
    description_zh: "调节电压和电阻并观察电流变化，用可视化方式理解 I=U/R 的定量关系。",
    difficulty: 1,
    interactive_elements: ["调节电压", "调节电阻", "观察电流"],
    learning_goals: ["掌握欧姆定律", "判断变量关系", "解释电路变化"],
    duration_minutes: 12,
  }),
  sim({
    id: "density",
    name_en: "Density",
    name_zh: "密度",
    subject: "physics",
    topics: ["密度", "质量", "体积", "浮力"],
    grade_range: [7, 9],
    description_zh: "比较不同物体的质量、体积和浮沉情况，帮助学生把密度公式和物理直觉结合起来。",
    difficulty: 1,
    interactive_elements: ["选择材料", "改变体积", "放入液体"],
    learning_goals: ["计算密度", "比较材料差异", "解释浮沉现象"],
    duration_minutes: 15,
  }),
  sim({
    id: "geometric-optics",
    name_en: "Geometric Optics",
    name_zh: "几何光学",
    subject: "physics",
    topics: ["透镜", "折射", "成像", "焦距"],
    grade_range: [8, 10],
    description_zh: "移动物体、透镜和屏幕，观察光线传播和成像位置，适合探究凸透镜成像规律。",
    difficulty: 2,
    interactive_elements: ["移动透镜", "拖动物体", "观察光线"],
    learning_goals: ["理解透镜成像", "认识焦距作用", "描述实像虚像"],
    duration_minutes: 20,
  }),
  sim({
    id: "masses-and-springs",
    name_en: "Masses and Springs",
    name_zh: "弹簧振子",
    subject: "physics",
    topics: ["简谐运动", "弹簧", "振动", "阻尼"],
    grade_range: [9, 11],
    description_zh: "改变质量、弹簧和阻尼，观察振子的周期和幅度，理解弹簧振动中的能量与运动关系。",
    difficulty: 2,
    interactive_elements: ["悬挂质量", "调节阻尼", "测量周期"],
    learning_goals: ["认识简谐运动", "比较周期因素", "解释阻尼影响"],
    duration_minutes: 18,
  }),
  sim({
    id: "friction",
    name_en: "Friction",
    name_zh: "摩擦力",
    subject: "physics",
    topics: ["静摩擦", "动摩擦", "摩擦系数"],
    grade_range: [8, 10],
    description_zh: "推拉不同物体并改变表面条件，观察静摩擦和动摩擦如何影响物体运动。",
    difficulty: 2,
    interactive_elements: ["改变表面", "施加外力", "观察摩擦"],
    learning_goals: ["区分静摩擦动摩擦", "理解摩擦系数", "分析受力变化"],
    duration_minutes: 16,
  }),
  sim({
    id: "vector-addition",
    name_en: "Vector Addition",
    name_zh: "向量相加",
    subject: "physics",
    topics: ["向量", "合力", "分力", "平行四边形法则"],
    grade_range: [9, 11],
    description_zh: "拖拽多个向量并观察合向量，帮助学生理解向量加法、分解和几何表示。",
    difficulty: 2,
    interactive_elements: ["拖拽向量", "显示合向量", "分解分量"],
    learning_goals: ["掌握向量加法", "理解合力分力", "应用平行四边形法则"],
    duration_minutes: 16,
  }),
  sim({
    id: "coulombs-law",
    name_en: "Coulomb's Law",
    name_zh: "库仑定律",
    subject: "physics",
    topics: ["电荷", "静电力", "库仑定律"],
    grade_range: [10, 12],
    description_zh: "改变电荷量和距离，观察静电力大小与方向，理解库仑定律中的平方反比关系。",
    difficulty: 3,
    interactive_elements: ["调节电荷量", "改变距离", "观察力矢量"],
    learning_goals: ["理解静电相互作用", "应用库仑定律", "解释距离影响"],
    duration_minutes: 18,
  }),
]

export const PHET_SIM_BY_ID = new Map(PHET_SIMS.map((simItem) => [simItem.id, simItem]))
