import React from "react"
import { FileText, Download } from "lucide-react"

interface ReportProps {
  content: string
}

export default function ReportRenderer({ content }: ReportProps) {
  // 简单的 Markdown 标题解析（为了不让你安装额外插件，我们手动处理简单的格式）
  const formatText = (text: string) => {
    return text.split('\n').map((line, index) => {
      // 处理标题 (### 或 ##)
      if (line.startsWith('### ')) {
        return <h3 key={index} className="text-lg font-bold text-slate-800 mt-4 mb-2">{line.replace('### ', '')}</h3>
      }
      if (line.startsWith('## ')) {
        return <h2 key={index} className="text-xl font-bold text-slate-900 mt-6 mb-3 border-b pb-1">{line.replace('## ', '')}</h2>
      }
      // 处理列表
      if (line.trim().startsWith('- ')) {
        return <li key={index} className="ml-4 list-disc text-slate-700">{line.replace('- ', '')}</li>
      }
      // 普通段落
      if (line.trim() === '') {
        return <br key={index} />
      }
      return <p key={index} className="mb-2 text-slate-700 leading-relaxed">{line}</p>
    })
  }

  return (
    <div className="w-full max-w-4xl mx-auto bg-white rounded-lg shadow-xl overflow-hidden border border-slate-200">
      {/* 顶部装饰条 */}
      <div className="h-2 bg-gradient-to-r from-blue-400 to-indigo-500"></div>
      
      {/* 报告头部 */}
      <div className="p-8 border-b border-slate-100 flex justify-between items-start bg-slate-50/50">
        <div className="flex gap-4">
          <div className="p-3 bg-white rounded-lg shadow-sm border border-slate-100">
            <FileText className="w-8 h-8 text-blue-600" />
          </div>
          <div>
            <h2 className="text-2xl font-bold text-slate-800">作文批改报告</h2>
            <p className="text-slate-500 text-sm mt-1">AI 深度诊断 · 建议阅读时间 3 分钟</p>
          </div>
        </div>
        <button className="hidden md:flex items-center gap-2 px-4 py-2 text-sm font-medium text-slate-600 bg-white border border-slate-200 rounded-lg hover:bg-slate-50 transition-colors">
          <Download className="w-4 h-4" />
          导出 PDF
        </button>
      </div>

      {/* 报告正文 (模拟纸张质感) */}
      <div className="p-8 md:p-12 bg-white min-h-[400px]">
        <article className="prose prose-slate max-w-none">
          {formatText(content)}
        </article>
      </div>

      {/* 底部页脚 */}
      <div className="bg-slate-50 px-8 py-4 border-t border-slate-100 text-center text-xs text-slate-400">
        Generated by AI Essay Engine • 仅供参考
      </div>
    </div>
  )
}