/**
 * 🖌 v2 智能体注册表
 *
 * 所有 22 个智能体的 v2 视觉元数据集中在这里。
 * 与 lib/dify-credentials.ts 等业务侧的 model key 对齐。
 */

import {
  PenLine,
  GraduationCap,
  Sparkles,
  Image as ImageIcon,
  Music,
  Calculator,
  BookOpen,
  HelpCircle,
  Layers3,
  Clipboard,
  Users,
  ScrollText,
  Award,
  Lightbulb,
  Globe,
  Briefcase,
  Mic,
  Megaphone,
  type LucideIcon,
} from "lucide-react"
import type { AgentDefinition } from "./types"

export const AGENT_REGISTRY: Record<string, AgentDefinition> = {
  standard: {
    model: "standard",
    name: "作文批改",
    description: "上传作文，逐段批注 + 升格建议",
    group: "writing",
    artifactType: "essay-review",
    priceLabel: "100 积分/次",
    icon: PenLine as LucideIcon,
  },
  "general-chat": {
    model: "general-chat",
    name: "通用对话",
    description: "日常学习问答",
    group: "general",
    artifactType: "markdown",
    priceLabel: "按字数计费",
    icon: Sparkles as LucideIcon,
  },
  "teaching-pro": {
    model: "teaching-pro",
    name: "教学评 Pro",
    description: "教案、点评报告、班级公告",
    group: "teaching",
    artifactType: "markdown",
    priceLabel: "100 积分起",
    memberOnly: false,
    icon: GraduationCap as LucideIcon,
  },
  "ai-writing-paper": {
    model: "ai-writing-paper",
    name: "论文写作",
    description: "结构化论文初稿 + 引用整理",
    group: "writing",
    artifactType: "markdown",
    priceLabel: "100 积分起",
    icon: ScrollText as LucideIcon,
  },
  "zhongying-essay": {
    model: "zhongying-essay",
    name: "中英作文",
    description: "中英对照创作与润色",
    group: "writing",
    artifactType: "markdown",
    priceLabel: "100 积分起",
    icon: BookOpen as LucideIcon,
  },
  "reading-report": {
    model: "reading-report",
    name: "读书报告",
    description: "读后感与读书笔记",
    group: "writing",
    artifactType: "markdown",
    priceLabel: "100 积分起",
    icon: BookOpen as LucideIcon,
  },
  "experiment-report": {
    model: "experiment-report",
    name: "实验报告",
    description: "实验目的、过程、结论结构化",
    group: "writing",
    artifactType: "markdown",
    priceLabel: "100 积分起",
    icon: Lightbulb as LucideIcon,
  },
  "study-abroad": {
    model: "study-abroad",
    name: "留学文书",
    description: "PS / SOP / Essay 多轮打磨",
    group: "writing",
    artifactType: "markdown",
    priceLabel: "100 积分起",
    icon: Globe as LucideIcon,
  },
  "resume-optimize": {
    model: "resume-optimize",
    name: "简历优化",
    description: "升级你的求职简历",
    group: "writing",
    artifactType: "markdown",
    priceLabel: "20 积分起",
    icon: Briefcase as LucideIcon,
  },
  "speech-defense": {
    model: "speech-defense",
    name: "演讲答辩",
    description: "答辩 / 演讲稿 / 即兴演讲",
    group: "writing",
    artifactType: "markdown",
    priceLabel: "20 积分起",
    icon: Mic as LucideIcon,
  },
  "school-wechat": {
    model: "school-wechat",
    name: "校园文案",
    description: "校园活动 / 公众号 / 海报文案",
    group: "writing",
    artifactType: "markdown",
    priceLabel: "20 积分起",
    icon: Megaphone as LucideIcon,
  },
  "beike-pro": {
    model: "beike-pro",
    name: "备课 Pro",
    description: "教案 / 课程目标 / 板书",
    group: "teaching",
    artifactType: "markdown",
    priceLabel: "100 积分起",
    icon: GraduationCap as LucideIcon,
  },
  banzhuren: {
    model: "banzhuren",
    name: "班主任助手",
    description: "学生评语、家长沟通、班级管理",
    group: "teaching",
    artifactType: "markdown",
    priceLabel: "100 积分起",
    icon: Users as LucideIcon,
  },
  "quanquan-math": {
    model: "quanquan-math",
    name: "全学段数学",
    description: "数学问题分步讲解",
    group: "subject",
    artifactType: "markdown",
    priceLabel: "20 积分起",
    icon: Calculator as LucideIcon,
  },
  "quanquan-english": {
    model: "quanquan-english",
    name: "全学段英语",
    description: "英语题翻译与讲解",
    group: "subject",
    artifactType: "markdown",
    priceLabel: "20 积分起",
    icon: BookOpen as LucideIcon,
  },
  "vocab-card": {
    model: "vocab-card",
    name: "词境记忆卡",
    description: "单词卡片 + 记忆故事 + 发音",
    group: "subject",
    artifactType: "vocab-card",
    priceLabel: "20 积分起",
    icon: Layers3 as LucideIcon,
  },
  problem: {
    model: "problem",
    name: "题目解析",
    description: "拍题或输入题干 → 分步讲解",
    group: "subject",
    artifactType: "markdown",
    priceLabel: "按字数计费",
    icon: HelpCircle as LucideIcon,
  },
  "open-claw": {
    model: "open-claw",
    name: "OpenClaw 演示页",
    description: "生成完整 PPT / 网页",
    group: "creative",
    artifactType: "markdown",
    priceLabel: "高级模型",
    icon: Clipboard as LucideIcon,
  },
  "banana-2-pro": {
    model: "banana-2-pro",
    name: "Banana 2 Pro 4K",
    description: "高质量图像生成（4K 大图）",
    group: "creative",
    artifactType: "markdown",
    priceLabel: "165 积分/张",
    icon: ImageIcon as LucideIcon,
  },
  "gpt-image-2": {
    model: "gpt-image-2",
    name: "GPT Image 2",
    description: "高质量 4K 图像生成与修图",
    group: "creative",
    artifactType: "markdown",
    priceLabel: "260 积分/张",
    memberOnly: true,
    icon: ImageIcon as LucideIcon,
  },
  "gpt-image-1": {
    model: "gpt-image-1",
    name: "GPT Image 1",
    description: "标准图像生成",
    group: "creative",
    artifactType: "markdown",
    priceLabel: "150 积分/张",
    icon: ImageIcon as LucideIcon,
  },
  "suno-v5": {
    model: "suno-v5",
    name: "Suno V5 音乐",
    description: "AI 作词 + 作曲 + 生成完整歌曲",
    group: "creative",
    artifactType: "markdown",
    priceLabel: "100 积分起",
    icon: Music as LucideIcon,
  },
  "all-in-one-agent": {
    model: "all-in-one-agent",
    name: "全能超级智能体",
    description: "自动选择合适工具完成复杂任务",
    group: "general",
    artifactType: "markdown",
    priceLabel: "按 Token 计费",
    icon: Award as LucideIcon,
  },
}

/** 按组分类输出 */
export const AGENT_GROUPS: Array<{ key: AgentDefinition["group"]; label: string }> = [
  { key: "general", label: "通用" },
  { key: "writing", label: "写作类" },
  { key: "teaching", label: "教学类" },
  { key: "subject", label: "学科类" },
  { key: "creative", label: "创作类" },
]

export function getAgentByModel(model: string | null | undefined): AgentDefinition | null {
  if (!model) return null
  return AGENT_REGISTRY[model] ?? null
}

export function listAgentsByGroup(group: AgentDefinition["group"]) {
  return Object.values(AGENT_REGISTRY).filter((a) => a.group === group)
}
