export type OpenClawSkillCategory =
  | "核心工具"
  | "PPT 与演示"
  | "论文与学术"
  | "中文写作"
  | "英语学习"
  | "数学教学"
  | "班主任与德育"
  | "小学作文"
  | "初高中作文"
  | "教学备课"
  | "其他技能"

export type OpenClawSkill = {
  id: string
  name: string
  category: OpenClawSkillCategory
  description: string
  tags: string[]
}

export const OPENCLAW_SKILL_CATEGORIES: OpenClawSkillCategory[] = [
  "核心工具",
  "PPT 与演示",
  "论文与学术",
  "中文写作",
  "英语学习",
  "数学教学",
  "班主任与德育",
  "小学作文",
  "初高中作文",
  "教学备课",
  "其他技能",
]

export const OPENCLAW_SKILLS: OpenClawSkill[] = [
  {
    id: "clawhub",
    name: "ClawHub 技能中心",
    category: "核心工具",
    description: "用于查看、管理和调用智能体技能入口，适合需要先找能力再执行任务的场景。",
    tags: ["技能中心", "能力管理", "智能体"],
  },
  {
    id: "healthcheck",
    name: "运行健康检查",
    category: "核心工具",
    description: "检查当前任务处理状态和基础服务是否正常，适合排查任务无响应。",
    tags: ["健康检查", "诊断", "状态"],
  },
  {
    id: "node-connect",
    name: "连接诊断助手",
    category: "核心工具",
    description: "用于检查任务连接和外部能力是否接通，帮助定位无响应或中断问题。",
    tags: ["连接", "诊断", "调试"],
  },
  {
    id: "skill-creator",
    name: "技能创建助手",
    category: "核心工具",
    description: "帮助把一个固定流程整理成可复用技能，适合沉淀网站、教学或创作步骤。",
    tags: ["创建技能", "步骤", "复用"],
  },
  {
    id: "taskflow",
    name: "任务流编排助手",
    category: "核心工具",
    description: "把复杂任务拆成步骤和交付物，适合多阶段创作、资料处理和自动化任务。",
    tags: ["任务流", "编排", "多步骤"],
  },
  {
    id: "taskflow-inbox-triage",
    name: "任务收件箱整理",
    category: "核心工具",
    description: "对输入的任务、消息和待办进行分类、优先级判断和下一步安排。",
    tags: ["待办", "分拣", "效率"],
  },
  {
    id: "video-frames",
    name: "视频帧分析助手",
    category: "其他技能",
    description: "用于从视频画面中提取关键帧、整理镜头内容和辅助生成视频分析说明。",
    tags: ["视频", "关键帧", "分析"],
  },
  {
    id: "weather",
    name: "天气查询助手",
    category: "其他技能",
    description: "查询天气信息并整理成易读说明，适合出行、活动安排和校园通知场景。",
    tags: ["天气", "查询", "出行"],
  },
  {
    id: "academic-thesis-review",
    name: "管理类硕士论文评审",
    category: "论文与学术",
    description: "面向 MBA、MEM、MPA 等管理类硕士论文，提供审阅、评估和修改建议。",
    tags: ["论文评审", "管理类硕士", "修改建议"],
  },
  {
    id: "ZeeLin Auto-PPT",
    name: "ZeeLin 自动 PPT",
    category: "PPT 与演示",
    description: "根据主题、资料或大纲自动生成演示结构，适合汇报、课程和路演初稿。",
    tags: ["PPT", "自动生成", "演示"],
  },
  {
    id: "bazi",
    name: "八字分析助手",
    category: "其他技能",
    description: "用于传统命理方向的基础分析和文字整理，适合娱乐、文化内容创作场景。",
    tags: ["八字", "文化", "内容"],
  },
  {
    id: "Chinese",
    name: "中文自然润色助手",
    category: "中文写作",
    description: "将不自然、机械感强的中文改得更顺畅、更有人味，同时尽量不改变核心意思。",
    tags: ["中文润色", "自然表达", "校对"],
  },
  {
    id: "vocab-master",
    name: "词汇记忆大师",
    category: "英语学习",
    description: "围绕英文单词生成释义、例句、记忆故事和复习提示，帮助学生更牢地记词。",
    tags: ["单词", "记忆", "例句"],
  },
  {
    id: "english-bestie",
    name: "英语学习搭子",
    category: "英语学习",
    description: "用陪伴式口吻进行英语表达修改、学习建议和日常练习互动。",
    tags: ["英语陪练", "表达", "互动"],
  },
  {
    id: "english-learning-coach",
    name: "英语学习教练",
    category: "英语学习",
    description: "为英语学习制定计划、纠错和阶段训练方案，适合长期提升听说读写能力。",
    tags: ["学习计划", "英语提升", "训练"],
  },
  {
    id: "frontend-slides",
    name: "前端幻灯片生成",
    category: "PPT 与演示",
    description: "生成带有网页质感的演示页面或幻灯片，适合技术汇报和可视化展示。",
    tags: ["前端", "幻灯片", "展示"],
  },
  {
    id: "Grammar",
    name: "通用语法纠错助手",
    category: "中文写作",
    description: "用于语法纠错、病句修正、拼写修正、标点优化和通用文本校对。",
    tags: ["语法", "病句", "标点"],
  },
  {
    id: "head-teacher-assistant",
    name: "班主任通用助手",
    category: "班主任与德育",
    description: "辅助班主任写通知、评语、家校沟通话术和班级事务材料。",
    tags: ["班主任", "家校沟通", "通知"],
  },
  {
    id: "khazix-writer",
    name: "公众号长文写作助手",
    category: "中文写作",
    description: "适合写公众号长文、按素材成稿、扩写成可发布文章、续写公众号内容。",
    tags: ["公众号", "长文", "素材成稿"],
  },
  {
    id: "Math",
    name: "数学通用助手",
    category: "数学教学",
    description: "处理数学题目讲解、思路拆解和知识点归纳，适合学生提问与教师备课。",
    tags: ["数学", "讲解", "知识点"],
  },
  {
    id: "math-edu-assistant",
    name: "数学教学助手",
    category: "数学教学",
    description: "面向教师的数学教学设计、例题组织和课堂讲解辅助。",
    tags: ["数学教学", "课堂", "例题"],
  },
  {
    id: "math-tutor-lite",
    name: "轻量数学家教",
    category: "数学教学",
    description: "用简明步骤辅导数学题，适合快速答疑、基础巩固和错题讲解。",
    tags: ["家教", "答疑", "错题"],
  },
  {
    id: "mba-thesis-advisor",
    name: "MBA 论文提升助手",
    category: "论文与学术",
    description: "面向 MBA 毕业论文优化，帮助提升结构、论证、案例和优秀论文标准匹配度。",
    tags: ["MBA", "论文优化", "案例"],
  },
  {
    id: "ppt-generator",
    name: "PPT 生成器",
    category: "PPT 与演示",
    description: "根据主题或资料生成 PPT 内容结构、页面标题和讲稿要点。",
    tags: ["PPT", "生成", "讲稿"],
  },
  {
    id: "ppt-workflow",
    name: "PPT 全流程助手",
    category: "PPT 与演示",
    description: "把 PPT 制作拆成选题、大纲、页面、讲稿和美化检查的完整流程。",
    tags: ["PPT", "全流程", "美化"],
  },
  {
    id: "shenxiang-9-shengji-zhongdengsheng",
    name: "九年级中等生升级助手",
    category: "教学备课",
    description: "面向九年级中等生，生成提分策略、学习建议和阶段性提升方案。",
    tags: ["九年级", "提分", "学习规划"],
  },
  {
    id: "shenxiang-banzhuren-banhuake-jiaxiaoyoushi",
    name: "班会课家校优势助手",
    category: "班主任与德育",
    description: "帮助设计班会课内容，突出家校协同、学生优势和正向成长表达。",
    tags: ["班会课", "家校", "成长"],
  },
  {
    id: "shenxiang-banzhuren-jiaxiao-maodun",
    name: "家校矛盾沟通助手",
    category: "班主任与德育",
    description: "为班主任提供家校矛盾沟通话术、处理步骤和风险较低的表达方式。",
    tags: ["家校矛盾", "沟通", "班主任"],
  },
  {
    id: "shenxiang-bei-huangdi-de-xinzhuang",
    name: "《皇帝的新装》教学助手",
    category: "教学备课",
    description: "围绕《皇帝的新装》生成教学设计、问题链、课堂活动和文本解读。",
    tags: ["语文", "教学", "皇帝的新装"],
  },
  {
    id: "shenxiang-chuzhong-xiuxi-piyue",
    name: "初中作文批阅助手",
    category: "初高中作文",
    description: "适合初中作文批改、润色、点评和升格建议。",
    tags: ["初中作文", "批改", "升格"],
  },
  {
    id: "shenxiang-expert-persona",
    name: "专家人格设定助手",
    category: "其他技能",
    description: "为复杂任务创建专家角色、回答风格和评估标准，适合定制化创作。",
    tags: ["专家角色", "设定", "提示词"],
  },
  {
    id: "shenxiang-gaozhong-lunshuowen",
    name: "高中论述文升格助手",
    category: "初高中作文",
    description: "帮助高中论述文升格，强化逻辑、论证深度和表达质量。",
    tags: ["高中", "论述文", "升格"],
  },
  {
    id: "shenxiang-gaozhong-xiangle-pingjia",
    name: "高中香乐评价助手",
    category: "教学备课",
    description: "用于高中语文或综合评价场景，生成更细致的学习表现评价与建议。",
    tags: ["高中", "评价", "教学"],
  },
  {
    id: "shenxiang-gaozhong-yingyu-zuowen",
    name: "高中英语作文批改助手",
    category: "英语学习",
    description: "适合高中英语作文批改、120 词作文优化、表达升级和错误纠正。",
    tags: ["高中英语", "作文批改", "语法"],
  },
  {
    id: "shenxiang-literary-style-deconstruct-and-universal-imitation",
    name: "文学风格拆解仿写",
    category: "中文写作",
    description: "拆解优秀文本风格并生成可迁移的仿写方法，适合散文、作文和文案训练。",
    tags: ["风格拆解", "仿写", "文学"],
  },
  {
    id: "shenxiang-lunshuowen",
    name: "高中论述文生成助手",
    category: "初高中作文",
    description: "根据题目直接生成高中论述文或议论文，适合从题目到成文。",
    tags: ["高中作文", "论述文", "成文"],
  },
  {
    id: "shenxiang-lunwen-shenping",
    name: "论文审稿诊断助手",
    category: "论文与学术",
    description: "提供审稿式论文诊断、学术自查、问题定位和修改方向。",
    tags: ["论文诊断", "审稿", "自查"],
  },
  {
    id: "shenxiang-paper-review-v5",
    name: "投稿前终检助手",
    category: "论文与学术",
    description: "用于投稿前排雷、降重整改、AIGC 风险检查和终稿质量把关。",
    tags: ["投稿", "终检", "AIGC"],
  },
  {
    id: "shenxiang-suicai-bianlun-geshen",
    name: "素材辩论个性化升格",
    category: "中文写作",
    description: "把普通素材转化为更有辨析度和表达力度的辩论或议论内容。",
    tags: ["素材", "辩论", "升格"],
  },
  {
    id: "shenxiang-suicai-bianlunshuowen",
    name: "素材辩论说明文助手",
    category: "中文写作",
    description: "将素材整理成辩论式说明或议论表达，适合写作训练和课堂展示。",
    tags: ["素材整理", "说明", "议论"],
  },
  {
    id: "shenxiang-taohuayuanji-jiaoxue",
    name: "《桃花源记》教学助手",
    category: "教学备课",
    description: "围绕《桃花源记》生成教学设计、文本细读、问题链和课堂活动。",
    tags: ["语文", "桃花源记", "备课"],
  },
  {
    id: "shenxiang-xiaoxue-5grade-zhengwen",
    name: "五年级征文润色助手",
    category: "小学作文",
    description: "面向五年级征文，提升文章文学性、结构完整度和表达感染力。",
    tags: ["五年级", "征文", "润色"],
  },
  {
    id: "shenxiang-xiaoxue-psychology-comment",
    name: "小学心理评语助手",
    category: "班主任与德育",
    description: "为小学生生成温和、具体、有支持感的心理观察评语与成长建议。",
    tags: ["小学", "心理", "评语"],
  },
  {
    id: "shenxiang-xiaoxue-xiangxiang-zuowen",
    name: "小学想象作文助手",
    category: "小学作文",
    description: "适合童话、幻想、拟人等想象类作文批改与创意提升。",
    tags: ["想象作文", "童话", "创意"],
  },
  {
    id: "shenxiang-xiaoxue-xinli-beike",
    name: "小学心理课备课助手",
    category: "教学备课",
    description: "帮助设计小学心理健康课活动、导入、问题和课堂流程。",
    tags: ["心理课", "小学", "备课"],
  },
  {
    id: "shenxiang-xiaoxue-zuowen-piyue",
    name: "小学低段记叙文助手",
    category: "小学作文",
    description: "适合 1-3 年级低段记叙文点评、润色和基础表达提升。",
    tags: ["低年级", "记叙文", "点评"],
  },
  {
    id: "shenxiang-xiaoxuezuowen",
    name: "小学生作文全程升级助手",
    category: "小学作文",
    description: "面向 1-6 年级小学生作文，提供多阶段升级、修改和展示。",
    tags: ["小学作文", "全程升级", "修改"],
  },
  {
    id: "shenxiang-xueweipigai-revise",
    name: "小学作文精批细改助手",
    category: "小学作文",
    description: "适合小学作文逐句精批、家长辅导场景和细致修改建议。",
    tags: ["精批", "逐句修改", "家长辅导"],
  },
  {
    id: "shenxiang-yi-lunwen-piyue",
    name: "议论文批改助手",
    category: "初高中作文",
    description: "适合初高中议论文批改、论证强化、结构调整和观点表达优化。",
    tags: ["议论文", "批改", "论证"],
  },
  {
    id: "shenxiang-youji-jiaoxue",
    name: "游记教学助手",
    category: "教学备课",
    description: "用于游记类文本教学，生成阅读问题、写法拆解和课堂训练活动。",
    tags: ["游记", "教学", "写法"],
  },
  {
    id: "shenxiang-zuowen-shengge",
    name: "散文哲思风升格助手",
    category: "初高中作文",
    description: "适合散文升格、哲思风润色、林清玄风格方向的表达优化。",
    tags: ["散文", "哲思", "升格"],
  },
  {
    id: "shenxiang-zuowen-zhangxiaofeng",
    name: "张晓风风格润色助手",
    category: "初高中作文",
    description: "适合张晓风风格、春之怀古式仿写和散文语言润色。",
    tags: ["张晓风", "散文", "仿写"],
  },
  {
    id: "math-mentor-simple",
    name: "简明数学导师",
    category: "数学教学",
    description: "用简洁方式讲清数学概念、步骤和易错点，适合快速辅导。",
    tags: ["数学导师", "概念", "易错点"],
  },
  {
    id: "teacher-kit-v4",
    name: "教师工具包 V4",
    category: "教学备课",
    description: "集合教案、作业、课堂活动和教学评价等教师常用材料生成能力。",
    tags: ["教师工具", "教案", "作业"],
  },
  {
    id: "thesis-helper",
    name: "论文结构与大纲助手",
    category: "论文与学术",
    description: "适合论文大纲、综述框架、摘要、引用格式和论文结构建议。",
    tags: ["论文大纲", "综述", "摘要"],
  },
  {
    id: "thu-thesis",
    name: "清华论文格式助手",
    category: "论文与学术",
    description: "面向论文格式、章节结构和学术表达规范检查，适合终稿整理。",
    tags: ["论文格式", "学术规范", "终稿"],
  },
  {
    id: "notebooklm",
    name: "资料笔记整理助手",
    category: "其他技能",
    description: "把资料、笔记和长文档整理成结构化摘要、问答和学习提纲。",
    tags: ["资料整理", "笔记", "摘要"],
  },
  {
    id: "AI Video Generation",
    name: "AI 视频生成助手",
    category: "其他技能",
    description: "根据主题、脚本或镜头需求生成视频创作方案和生成提示词。",
    tags: ["视频生成", "脚本", "提示词"],
  },
  {
    id: "xueersi-english-grammar-check",
    name: "英语语法讲解助手",
    category: "英语学习",
    description: "提供英语语法纠错和中文讲解，帮助理解错误原因和修改方法。",
    tags: ["英语语法", "纠错", "中文讲解"],
  },
  {
    id: "xueersi-math-word-problem",
    name: "数学应用题解析助手",
    category: "数学教学",
    description: "拆解数学应用题条件、关系和解题步骤，帮助学生理解题意。",
    tags: ["应用题", "解析", "步骤"],
  },
  {
    id: "zhejiao-xinxijishu-beike",
    name: "浙教信息技术备课",
    category: "教学备课",
    description: "面向浙教版信息技术课程，生成教学设计、活动安排和课堂任务。",
    tags: ["信息技术", "浙教版", "备课"],
  },
]

export function getOpenClawSkillById(id: string | null | undefined) {
  if (!id) return null
  return OPENCLAW_SKILLS.find((skill) => skill.id === id) ?? null
}
