"use client"

import type { ElementType } from "react"
import type { ModelKey } from "@/components/ModelLogo"
import {
  Baby,
  BookA,
  BookMarked,
  BookOpenCheck,
  BookOpenText,
  Bot,
  Box,
  BriefcaseBusiness,
  Camera,
  ClipboardCheck,
  ClipboardList,
  FileAudio,
  FileImage,
  FileUp,
  Flower2,
  GraduationCap,
  Languages,
  Leaf,
  Medal,
  MessageSquareQuote,
  MessageSquareText,
  Newspaper,
  PanelTop,
  PenLine,
  Presentation,
  Scale,
  School,
  Search,
  SearchCheck,
  ShieldCheck,
  Sparkle,
  Sparkles,
  SpellCheck,
  TrendingUp,
  Wand,
  Wand2,
} from "lucide-react"
import {
  IconAllInOne,
  IconBanzhuren,
  IconBeike,
  IconDiagnosis,
  IconEnglish,
  IconEssay,
  IconMath,
  IconMusic,
  IconOpenClaw,
  IconProblem,
  IconSuperAgent,
  IconTeaching,
  IconVocab,
  IconWebsiteAssistant,
  IconWriting,
} from "@/components/icons/v2"
import { CELLFORGE_EXTERNAL_URL } from "@/lib/tripo3d"
import { WORKFLOW_SKILL_IDS } from "@/lib/workflow-skill-agents"

export const CORE_AGENT_IDS = ["super-all-in-one-agent", "open-claw", "general-chat"] as const

export const AGENT_CATEGORIES = [
  { key: "recommended", label: "推荐" },
  { key: "general", label: "通用助手" },
  { key: "content-writing", label: "公众号与内容写作" },
  { key: "chinese-polish", label: "中文润色与纠错" },
  { key: "academic", label: "论文与学术" },
  { key: "k12-essay", label: "中小学作文" },
  { key: "primary-essay", label: "小学作文专项" },
  { key: "high-school-writing", label: "高中写作" },
  { key: "english-writing", label: "英语写作与语法" },
  { key: "teaching-subject", label: "教学与学科" },
  { key: "creative", label: "图像与创作" },
  { key: "models", label: "独立模型" },
  { key: "tools", label: "其他工具" },
] as const

export type AgentCategory = (typeof AGENT_CATEGORIES)[number]["label"]
export type AgentCategoryKey = (typeof AGENT_CATEGORIES)[number]["key"]

export type PlazaAgent = {
  id: string
  name: string
  category: AgentCategory
  description: string
  icon: ElementType
  href: string
  routeId: string
  skill?: string
  agent?: string
  workflowSkill?: boolean
  modelKey?: ModelKey
  tags: string[]
  badge?: string
  priceLabel?: string
  memberOnly?: boolean
  featured?: boolean
  external?: boolean
}

const workflowHref = (skill: string) => `/chat?agent=${encodeURIComponent(skill)}`

const workflowSkill = (
  id: string,
  name: string,
  category: AgentCategory,
  description: string,
  icon: ElementType,
  tags: string[],
): PlazaAgent => ({
  id,
  name,
  category,
  description,
  icon,
  href: workflowHref(id),
  routeId: `/chat?agent=${id}`,
  skill: id,
  workflowSkill: true,
  tags,
})

export const PLAZA_AGENTS: PlazaAgent[] = [
  {
    id: "super-all-in-one-agent",
    name: "超级全能智能体",
    category: "推荐",
    description: "接入顶级模型和综合能力，适合复杂问题拆解、长文写作、PPT、图像、视频、联网和多工具任务。",
    icon: IconSuperAgent,
    href: "/chat/super-all-in-one-agent",
    routeId: "/chat/super-all-in-one-agent",
    agent: "super-all-in-one-agent",
    modelKey: "super-all-in-one-agent",
    tags: ["顶级模型", "PPT", "图像", "视频", "论文", "联网"],
    badge: "核心",
    priceLabel: "按 Token 计费",
    featured: true,
  },
  {
    id: "open-claw",
    name: "OpenClaw",
    category: "推荐",
    description: "面向复杂创作与演示任务，可用于生成完整 PPT、网页、方案和多步骤创作内容。",
    icon: IconOpenClaw,
    href: "/chat/open-claw",
    routeId: "/chat/open-claw",
    agent: "open-claw",
    modelKey: "open-claw",
    tags: ["PPT", "网页", "方案", "多步骤创作"],
    badge: "核心",
    priceLabel: "高级模型",
    featured: true,
  },
  {
    id: "general-chat",
    name: "网站助手",
    category: "推荐",
    description: "帮助用户了解网站功能、套餐权益、使用路径和常见问题，适合新用户快速上手。",
    icon: IconWebsiteAssistant,
    href: "/chat/general-chat",
    routeId: "/chat/general-chat",
    agent: "general-chat",
    modelKey: "general-chat",
    tags: ["网站功能", "套餐权益", "新手指引", "常见问题"],
    badge: "核心",
    priceLabel: "按字数计费",
    featured: true,
  },

  {
    id: "all-in-one-agent",
    name: "数学图片与动画生成器",
    category: "通用助手",
    description: "自动选择合适工具完成复杂任务，适合数学图像、动画、文件和综合创作。",
    icon: IconAllInOne,
    href: "/chat/all-in-one-agent",
    routeId: "/chat/all-in-one-agent",
    agent: "all-in-one-agent",
    modelKey: "all-in-one-agent",
    tags: ["数学图片", "动画", "文件", "综合任务"],
    priceLabel: "按 Token 计费",
    featured: true,
  },
  {
    id: "teacher-agent-builder",
    name: "教师自定义智能体",
    category: "通用助手",
    description: "教师可创建面向班级和学科的专属智能体，支持分享给学生使用。",
    icon: Bot,
    href: "/teacher/agents",
    routeId: "/teacher/agents",
    agent: "teacher-agent",
    tags: ["教师", "自定义", "分享码", "班级"],
  },

  {
    id: "gpt-5",
    name: "ChatGPT 5.5",
    category: "独立模型",
    description: "通用推理、写作和复杂问题拆解，适合直接进入模型原生对话。",
    icon: Sparkles,
    href: "/chat/gpt-5",
    routeId: "/chat/gpt-5",
    agent: "gpt-5",
    modelKey: "gpt-5",
    tags: ["独立模型", "推理", "写作"],
    badge: "新",
  },
  {
    id: "claude-opus",
    name: "Claude Opus",
    category: "独立模型",
    description: "长文理解、结构分析和严谨润色，适合复杂文本任务。",
    icon: BookOpenText,
    href: "/chat/claude-opus",
    routeId: "/chat/claude-opus",
    agent: "claude-opus",
    modelKey: "claude-opus",
    tags: ["独立模型", "长文", "分析", "润色"],
  },
  {
    id: "gemini-pro",
    name: "Gemini Pro",
    category: "独立模型",
    description: "多模态理解、资料整理和快速问答，适合图文混合资料处理。",
    icon: Sparkle,
    href: "/chat/gemini-pro",
    routeId: "/chat/gemini-pro",
    agent: "gemini-pro",
    modelKey: "gemini-pro",
    tags: ["独立模型", "多模态", "资料整理"],
  },
  {
    id: "grok-4.2",
    name: "Grok 4.2",
    category: "独立模型",
    description: "开放式探索、灵感发散和实时型提问，适合快速探索问题。",
    icon: MessageSquareText,
    href: "/chat/grok-4.2",
    routeId: "/chat/grok-4.2",
    agent: "grok-4.2",
    modelKey: "grok-4.2",
    tags: ["独立模型", "探索", "灵感"],
  },

  {
    id: "standard",
    name: "作文批改",
    category: "中小学作文",
    description: "上传作文，逐段批注、评分诊断并给出升格建议。",
    icon: IconEssay,
    href: "/chat/standard",
    routeId: "/chat/standard",
    agent: "standard",
    modelKey: "standard",
    tags: ["作文批改", "逐段批注", "升格"],
    badge: "推荐",
    priceLabel: "100 积分/次",
    featured: true,
  },
  {
    id: "ai-writing-paper",
    name: "论文写作",
    category: "论文与学术",
    description: "结构化论文初稿、摘要、章节框架和引用整理。",
    icon: IconWriting,
    href: "/chat/ai-writing-paper",
    routeId: "/chat/ai-writing-paper",
    agent: "ai-writing-paper",
    modelKey: "ai-writing-paper",
    tags: ["论文", "初稿", "引用", "摘要"],
    priceLabel: "100 积分起",
  },
  {
    id: "zhongying-essay",
    name: "中英作文",
    category: "英语写作与语法",
    description: "中英对照创作、作文润色、语法纠错和表达升级。",
    icon: IconEnglish,
    href: "/chat/zhongying-essay",
    routeId: "/chat/zhongying-essay",
    agent: "zhongying-essay",
    modelKey: "zhongying-essay",
    tags: ["中英作文", "润色", "语法", "表达升级"],
    priceLabel: "100 积分起",
  },
  {
    id: "reading-report",
    name: "读书报告",
    category: "公众号与内容写作",
    description: "生成读后感、读书笔记和阅读报告，帮助提炼书籍核心观点。",
    icon: BookOpenCheck,
    href: "/chat/reading-report",
    routeId: "/chat/reading-report",
    agent: "reading-report",
    modelKey: "reading-report",
    tags: ["读后感", "读书笔记", "报告"],
    priceLabel: "100 积分起",
  },
  {
    id: "experiment-report",
    name: "实验报告",
    category: "论文与学术",
    description: "整理实验目的、过程、数据、结论和规范化报告结构。",
    icon: ClipboardList,
    href: "/chat/experiment-report",
    routeId: "/chat/experiment-report",
    agent: "experiment-report",
    modelKey: "experiment-report",
    tags: ["实验报告", "数据", "结论", "理工科"],
    priceLabel: "100 积分起",
  },
  {
    id: "study-abroad",
    name: "留学文书",
    category: "公众号与内容写作",
    description: "PS、SOP、Essay 多轮打磨，挖掘个人经历和申请故事。",
    icon: GraduationCap,
    href: "/chat/study-abroad",
    routeId: "/chat/study-abroad",
    agent: "study-abroad",
    modelKey: "study-abroad",
    tags: ["留学", "PS", "SOP", "申请文书"],
    priceLabel: "100 积分起",
  },
  {
    id: "resume-optimize",
    name: "简历优化",
    category: "公众号与内容写作",
    description: "提炼校园经历、项目经历和求职亮点，生成更专业的简历表达。",
    icon: BriefcaseBusiness,
    href: "/chat/resume-optimize",
    routeId: "/chat/resume-optimize",
    agent: "resume-optimize",
    modelKey: "resume-optimize",
    tags: ["简历", "求职", "经历提炼"],
    priceLabel: "20 积分起",
  },
  {
    id: "speech-defense",
    name: "演讲答辩",
    category: "公众号与内容写作",
    description: "生成答辩稿、演讲稿、竞选稿和即兴演讲结构。",
    icon: MessageSquareQuote,
    href: "/chat/speech-defense",
    routeId: "/chat/speech-defense",
    agent: "speech-defense",
    modelKey: "speech-defense",
    tags: ["演讲", "答辩", "逐字稿"],
    priceLabel: "20 积分起",
  },
  {
    id: "school-wechat",
    name: "校园文案",
    category: "公众号与内容写作",
    description: "校园活动、公众号、海报和班级通知文案写作。",
    icon: Newspaper,
    href: "/chat/school-wechat",
    routeId: "/chat/school-wechat",
    agent: "school-wechat",
    modelKey: "school-wechat",
    tags: ["校园", "公众号", "海报文案"],
    priceLabel: "20 积分起",
  },

  {
    id: "teaching-pro",
    name: "教学评 Pro",
    category: "教学与学科",
    description: "生成教案、点评报告、班级公告和教学评价反馈。",
    icon: IconTeaching,
    href: "/chat/teaching-pro",
    routeId: "/chat/teaching-pro",
    agent: "teaching-pro",
    modelKey: "teaching-pro",
    tags: ["教学评", "教案", "点评报告"],
    priceLabel: "100 积分起",
  },
  {
    id: "beike-pro",
    name: "备课 Pro",
    category: "教学与学科",
    description: "辅助生成教案、课程目标、教学流程和板书设计。",
    icon: IconBeike,
    href: "/chat/beike-pro",
    routeId: "/chat/beike-pro",
    agent: "beike-pro",
    modelKey: "beike-pro",
    tags: ["备课", "教案", "板书"],
    priceLabel: "100 积分起",
  },
  {
    id: "banzhuren",
    name: "班主任助手",
    category: "教学与学科",
    description: "学生评语、家长沟通、班级管理和日常通知写作。",
    icon: IconBanzhuren,
    href: "/chat/banzhuren",
    routeId: "/chat/banzhuren",
    agent: "banzhuren",
    modelKey: "banzhuren",
    tags: ["班主任", "评语", "家校沟通"],
    priceLabel: "100 积分起",
  },
  {
    id: "quanquan-math",
    name: "全学段数学",
    category: "教学与学科",
    description: "数学问题分步讲解、解题思路梳理和错因分析。",
    icon: IconMath,
    href: "/chat/quanquan-math",
    routeId: "/chat/quanquan-math",
    agent: "quanquan-math",
    modelKey: "quanquan-math",
    tags: ["数学", "分步讲解", "错因"],
    priceLabel: "20 积分起",
  },
  {
    id: "quanquan-english",
    name: "全学段英语",
    category: "教学与学科",
    description: "英语题翻译、知识点讲解、阅读理解和表达辅导。",
    icon: IconEnglish,
    href: "/chat/quanquan-english",
    routeId: "/chat/quanquan-english",
    agent: "quanquan-english",
    modelKey: "quanquan-english",
    tags: ["英语", "翻译", "阅读理解"],
    priceLabel: "20 积分起",
  },
  {
    id: "problem",
    name: "题目解析",
    category: "教学与学科",
    description: "拍题或输入题干，输出分步解析、知识点和易错提醒。",
    icon: IconProblem,
    href: "/chat/problem",
    routeId: "/chat/problem",
    agent: "problem",
    modelKey: "problem",
    tags: ["拍题", "题目解析", "知识点"],
    priceLabel: "按字数计费",
  },
  {
    id: "worksheet-diagnosis",
    name: "拍卷诊断海报",
    category: "教学与学科",
    description: "上传试卷和作业图片，模型批改归因后生成家校沟通诊断海报。",
    icon: IconDiagnosis,
    href: "/worksheet-diagnosis",
    routeId: "/worksheet-diagnosis",
    agent: "worksheet-diagnosis",
    tags: ["试卷", "作业", "诊断海报", "Image 2"],
    badge: "推荐",
    featured: true,
  },
  {
    id: "flashcards",
    name: "闪卡复习",
    category: "教学与学科",
    description: "把学习材料转换为可复习闪卡，支持记忆跟踪和错题复盘。",
    icon: BookMarked,
    href: "/flashcards",
    routeId: "/flashcards",
    agent: "flashcards",
    tags: ["闪卡", "复习", "记忆"],
  },
  {
    id: "lab",
    name: "互动实验室",
    category: "教学与学科",
    description: "浏览数学与物理互动模拟实验，把公式、图像和现象连起来。",
    icon: School,
    href: "/lab",
    routeId: "/lab",
    agent: "phet-lab",
    tags: ["实验室", "数学", "物理", "PhET"],
  },

  {
    id: "vocab-card",
    name: "词境记忆卡",
    category: "英语写作与语法",
    description: "生成单词卡片、记忆故事、例句和发音，适合英语词汇复习。",
    icon: IconVocab,
    href: "/chat/vocab-card",
    routeId: "/chat/vocab-card",
    agent: "vocab-card",
    modelKey: "vocab-card",
    tags: ["单词", "例句", "发音", "记忆故事"],
    badge: "新",
    priceLabel: "20 积分起",
  },

  {
    id: "gemini-image",
    name: "Gemini 图像",
    category: "图像与创作",
    description: "Google Gemini 文生图与图像编辑工作台。",
    icon: FileImage,
    href: "/chat/gemini-image",
    routeId: "/chat/gemini-image",
    agent: "gemini-image",
    modelKey: "gemini-image",
    tags: ["图像生成", "图像编辑", "Gemini"],
    badge: "新",
  },
  {
    id: "banana-2-pro",
    name: "Banana 2 Pro",
    category: "图像与创作",
    description: "高质量图像生成与编辑，适合参考图驱动的创意任务。",
    icon: FileImage,
    href: "/chat/banana-2-pro",
    routeId: "/chat/banana-2-pro",
    agent: "banana-2-pro",
    modelKey: "banana-2-pro",
    tags: ["图像生成", "图像编辑", "Banana"],
    priceLabel: "图像计费",
  },
  {
    id: "gpt-image-2",
    name: "GPT Image 2",
    category: "图像与创作",
    description: "高质量图像生成与修图，支持不同尺寸和质量档位。",
    icon: FileImage,
    href: "/chat/gpt-image-2",
    routeId: "/chat/gpt-image-2",
    agent: "gpt-image-2",
    modelKey: "gpt-image-2",
    tags: ["Image 2", "图像生成", "修图"],
    badge: "推荐",
    priceLabel: "10-55 积分/张",
    featured: true,
  },
  {
    id: "gpt-image-1",
    name: "GPT Image 1",
    category: "图像与创作",
    description: "标准图像生成与编辑入口，适合稳定的常规生图任务。",
    icon: FileImage,
    href: "/chat/gpt-image-1",
    routeId: "/chat/gpt-image-1",
    agent: "gpt-image-1",
    modelKey: "gpt-image-1",
    tags: ["图像生成", "OpenAI", "编辑"],
    priceLabel: "图像计费",
  },
  {
    id: "suno-v5",
    name: "suno音乐创作",
    category: "图像与创作",
    description: "输入歌词、风格和创作要求，生成 AI 音乐作品。",
    icon: IconMusic,
    href: "/suno",
    routeId: "/suno",
    agent: "suno-v5",
    modelKey: "suno-v5",
    tags: ["音乐", "Suno", "歌词"],
    priceLabel: "100 积分起",
  },
  {
    id: "tripo3d",
    name: "3D 细胞工作台",
    category: "图像与创作",
    description: "生成和查看细胞 3D 场景与模型，适合生物教学演示。",
    icon: Box,
    href: CELLFORGE_EXTERNAL_URL,
    routeId: CELLFORGE_EXTERNAL_URL,
    agent: "cellforge-3d",
    tags: ["3D", "细胞", "生物", "演示"],
    badge: "3D",
    external: true,
  },
  {
    id: "image-prompt-reverse",
    name: "图像提示词反推",
    category: "图像与创作",
    description: "上传参考图，反推出可用于 Image 2 或 Gemini/Banana 的生成提示词。",
    icon: FileImage,
    href: "/tools#image-prompt-reverse",
    routeId: "/tools#image-prompt-reverse",
    agent: "image-prompt-reverse",
    tags: ["提示词", "反推", "图像生成"],
    badge: "工具",
  },

  {
    id: "document-process",
    name: "文档处理",
    category: "其他工具",
    description: "上传 PDF、Word、图片或文本，提取可继续加工的学习资料。",
    icon: FileUp,
    href: "/tools#document-process",
    routeId: "/tools#document-process",
    agent: "document-process",
    tags: ["PDF", "Word", "文档提取"],
  },
  {
    id: "ocr",
    name: "图片 OCR",
    category: "其他工具",
    description: "上传或拍照识别图片文字，适合资料整理和错题录入。",
    icon: Camera,
    href: "/tools#ocr",
    routeId: "/tools#ocr",
    agent: "ocr",
    tags: ["OCR", "拍照", "图片文字"],
  },
  {
    id: "presentation",
    name: "演示文稿",
    category: "其他工具",
    description: "把课件、汇报素材快速整理成演示结构。",
    icon: Presentation,
    href: "/tools#presentation",
    routeId: "/tools#presentation",
    agent: "presentation",
    tags: ["PPT", "课件", "演示"],
  },
  {
    id: "web-search",
    name: "网页搜索",
    category: "其他工具",
    description: "围绕一个问题抓取网页结果，辅助备课、调研和资料查找。",
    icon: Search,
    href: "/tools#web-search",
    routeId: "/tools#web-search",
    agent: "web-search",
    tags: ["搜索", "资料", "调研"],
  },
  {
    id: "sparkpage",
    name: "Sparkpage 综合报告",
    category: "其他工具",
    description: "输入主题，生成更完整的资料整理和综合分析结果。",
    icon: PanelTop,
    href: "/tools#sparkpage",
    routeId: "/tools#sparkpage",
    agent: "sparkpage",
    tags: ["综合报告", "资料整理", "分析"],
  },
  {
    id: "omnivoice-tts",
    name: "文字转语音",
    category: "其他工具",
    description: "把文本转换成可播放音频，支持服务器 OmniVoice 网关和音色选择。",
    icon: FileAudio,
    href: "/tools#tts",
    routeId: "/tools#tts",
    agent: "omnivoice-tts",
    tags: ["TTS", "语音", "音色"],
    badge: "语音",
  },
  {
    id: "tools-desk",
    name: "工具工作台",
    category: "其他工具",
    description: "集中使用图像反推、文档提取、OCR、演示文稿、搜索和语音工具。",
    icon: Wand2,
    href: "/tools",
    routeId: "/tools",
    agent: "tools-desk",
    tags: ["工具", "工作台", "集合入口"],
  },

  workflowSkill(
    "khazix-writer",
    "公众号长文写作助手",
    "公众号与内容写作",
    "适合写公众号长文、按素材成稿、扩写成可发布文章、续写公众号内容。",
    Newspaper,
    ["公众号", "长文", "素材成稿", "续写"],
  ),
  workflowSkill(
    "Chinese",
    "中文自然润色助手",
    "中文润色与纠错",
    "将不自然、机械感强的中文改得更顺畅、更有人味，同时尽量不改变核心意思。",
    Sparkles,
    ["中文润色", "自然表达", "去机械感"],
  ),
  workflowSkill(
    "Grammar",
    "通用语法纠错助手",
    "中文润色与纠错",
    "用于语法纠错、病句修正、拼写修正、标点优化和通用文本校对。",
    SpellCheck,
    ["语法", "校对", "病句", "标点"],
  ),
  workflowSkill(
    "thesis-helper",
    "论文结构与大纲助手",
    "论文与学术",
    "适合论文大纲、综述框架、摘要、引用格式和论文结构建议。",
    GraduationCap,
    ["论文", "大纲", "综述", "摘要"],
  ),
  workflowSkill(
    "mba-thesis-advisor",
    "MBA 论文提升助手",
    "论文与学术",
    "面向 MBA 毕业论文优化，帮助提升结构、论证、案例和优秀论文标准匹配度。",
    BriefcaseBusiness,
    ["MBA", "毕业论文", "案例", "论证"],
  ),
  workflowSkill(
    "academic-thesis-review",
    "管理类硕士论文评审助手",
    "论文与学术",
    "适合 MBA、MEM、MPA 等管理类硕士论文审阅、评估和修改建议。",
    ClipboardCheck,
    ["管理类硕士", "论文评审", "MBA", "MEM", "MPA"],
  ),
  workflowSkill(
    "shenxiang-lunwen-shenping",
    "论文审稿诊断助手",
    "论文与学术",
    "提供审稿式论文诊断、学术自查、问题定位和修改方向。",
    SearchCheck,
    ["审稿", "论文诊断", "学术自查"],
  ),
  workflowSkill(
    "shenxiang-paper-review-v5",
    "投稿前终检助手",
    "论文与学术",
    "用于投稿前排雷、降重整改、AIGC 风险检查和终稿质量把关。",
    ShieldCheck,
    ["投稿前", "终检", "降重", "AIGC"],
  ),
  workflowSkill(
    "shenxiang-chuzhong-xiuxi-piyue",
    "初中作文批阅助手",
    "中小学作文",
    "适合初中作文批改、润色、点评和升格建议。",
    BookMarked,
    ["初中作文", "批阅", "润色", "升格"],
  ),
  workflowSkill(
    "shenxiang-yi-lunwen-piyue",
    "议论文批改助手",
    "中小学作文",
    "适合初高中议论文批改、论证强化、结构调整和观点表达优化。",
    Scale,
    ["议论文", "论证", "结构调整"],
  ),
  workflowSkill(
    "shenxiang-lunshuowen",
    "高中论述文生成助手",
    "高中写作",
    "根据题目直接生成高中论述文或议论文，适合从题目到成文。",
    PenLine,
    ["高中", "论述文", "议论文生成"],
  ),
  workflowSkill(
    "shenxiang-gaozhong-lunshuowen",
    "高中论述文升格助手",
    "高中写作",
    "帮助高中论述文升格，强化逻辑、论证深度和表达质量。",
    TrendingUp,
    ["高中", "论述文", "升格", "逻辑"],
  ),
  workflowSkill(
    "shenxiang-zuowen-shengge",
    "散文哲思风升格助手",
    "中小学作文",
    "适合散文升格、哲思风润色、林清玄风格方向的表达优化。",
    Leaf,
    ["散文", "哲思风", "升格", "林清玄"],
  ),
  workflowSkill(
    "shenxiang-zuowen-zhangxiaofeng",
    "张晓风风格润色助手",
    "中小学作文",
    "适合张晓风风格、春之怀古式仿写和散文语言润色。",
    Flower2,
    ["张晓风", "仿写", "散文润色"],
  ),
  workflowSkill(
    "shenxiang-xiaoxuezuowen",
    "小学生作文全程升级助手",
    "小学作文专项",
    "面向 1-6 年级小学生作文，提供多阶段升级、修改和展示。",
    School,
    ["小学作文", "1-6年级", "全程升级"],
  ),
  workflowSkill(
    "shenxiang-xueweipigai-revise",
    "小学作文精批细改助手",
    "小学作文专项",
    "适合小学作文逐句精批、家长辅导场景和细致修改建议。",
    ClipboardList,
    ["小学作文", "精批细改", "家长辅导"],
  ),
  workflowSkill(
    "shenxiang-xiaoxue-zuowen-piyue",
    "小学低段记叙文助手",
    "小学作文专项",
    "适合 1-3 年级低段记叙文点评、润色和基础表达提升。",
    Baby,
    ["小学低段", "记叙文", "点评"],
  ),
  workflowSkill(
    "shenxiang-xiaoxue-xiangxiang-zuowen",
    "小学想象作文助手",
    "小学作文专项",
    "适合童话、幻想、拟人等想象类作文批改与创意提升。",
    Wand,
    ["想象作文", "童话", "幻想", "创意"],
  ),
  workflowSkill(
    "shenxiang-xiaoxue-5grade-zhengwen",
    "五年级征文润色助手",
    "小学作文专项",
    "面向五年级征文，提升文章文学性、结构完整度和表达感染力。",
    Medal,
    ["五年级", "征文", "润色", "文学性"],
  ),
  workflowSkill(
    "shenxiang-gaozhong-yingyu-zuowen",
    "高中英语作文批改助手",
    "英语写作与语法",
    "适合高中英语作文批改、120 词作文优化、表达升级和错误纠正。",
    Languages,
    ["高中英语", "作文批改", "120词", "表达升级"],
  ),
  workflowSkill(
    "xueersi-english-grammar-check",
    "英语语法讲解助手",
    "英语写作与语法",
    "提供英语语法纠错和中文讲解，帮助理解错误原因和修改方法。",
    BookA,
    ["英语语法", "中文讲解", "纠错"],
  ),
]

export function getAgentCategoryKey(category: AgentCategory): AgentCategoryKey {
  return AGENT_CATEGORIES.find((item) => item.label === category)?.key ?? "tools"
}

export function getCoreAgents() {
  return CORE_AGENT_IDS.map((id) => PLAZA_AGENTS.find((agent) => agent.id === id)).filter(Boolean) as PlazaAgent[]
}

if (process.env.NODE_ENV !== "production") {
  const missingWorkflowSkills = WORKFLOW_SKILL_IDS.filter(
    (id) => !PLAZA_AGENTS.some((agent) => agent.id === id && agent.workflowSkill),
  )
  if (missingWorkflowSkills.length > 0) {
    console.warn("[Agent Plaza] Missing workflow skill cards:", missingWorkflowSkills.join(", "))
  }
}
