import fs from "fs"
import path from "path"

const root = path.join(__dirname, "..")
const read = (relativePath: string) => fs.readFileSync(path.join(root, relativePath), "utf8")

describe("free trial monitor source contracts", () => {
  it("cron monitor route requires CRON_SECRET", () => {
    const source = read("app/api/cron/free-trial-monitor/route.ts")
    expect(source).toContain("CRON_SECRET")
    expect(source).toMatch(/status:\s*403/)
    expect(source).toContain("runFreeTrialMonitor")
  })

  it("admin monitor route requires admin verification", () => {
    const source = read("app/api/admin/free-trial-monitor/route.ts")
    expect(source).toContain("verifyAdminRequest")
    expect(source).toMatch(/status:\s*403/)
    expect(source).toContain("setRuntimeConfig")
  })

  it("monitor core only performs runtime flag stop-loss actions", () => {
    const source = read("lib/free-trial-monitor.ts")
    expect(source).toContain("disableFreeTrialConsumption")
    expect(source).toContain("disableFreeTrialCampaign")
    expect(source).toContain("checkRuntimeFlagsEndpoint")
    expect(source).toContain("runtime_flags_endpoint_unavailable")
    expect(source).toContain("fallbackRecent5m")
    expect(source).toContain("fallbackRecent30m")
    expect(source).toContain("fallbackPrevious30m")
    expect(source).toContain("checkUnexpectedRealCreditDebits")
    expect(source).toContain("unexpected_real_credit_debits")
    expect(source).toContain("credit_transactions")
    expect(source).toContain("trial_credit_usages")
    expect(source).toContain("Supabase 或网络瞬时失败不能单次关闭用户可见权益")
    expect(source).toContain("core_tables_missing")
    expect(source).toContain("autoStopLoss: false")
    expect(source).not.toContain('autoActions: ["disable_campaign", "disable_consumption"]')
    expect(source).toContain("matchedExpectedFallbackReferences")
    expect(source).toContain("trial_billing_real_credit_fallback")
    expect(source).toContain("isExpectedTrialRealCreditFallbackEvent")
    expect(source).not.toContain("fallbackCount: counts.trial_billing_real_credit_fallback")
    expect(source).not.toMatch(/from\("user_credits"\)\s*\.update/)
    expect(source).not.toMatch(/from\("orders"\)\s*\.update/)
    expect(source).not.toMatch(/from\("free_trial_grants"\)\s*\.delete/)
  })

  it("monitor script documents forbidden destructive operations by omission", () => {
    const source = read("scripts/monitor-free-trial.mjs")
    expect(source).toContain("free_trial_runtime_config")
    expect(source).toContain("monitor_incidents")
    expect(source).toContain("checkRuntimeFlagsEndpoint")
    expect(source).toContain("checkLocalMonitorFiles")
    expect(source).toContain("monitor_deployment_files_missing")
    expect(source).toContain("Supabase 或网络瞬时失败不能单次关闭用户可见权益")
    expect(source).toContain("core_tables_missing")
    expect(source).toContain("autoStopLoss: false")
    expect(source).not.toContain('autoActions: ["disable_campaign", "disable_consumption"]')
    expect(source).toContain("fallbackRecent5m")
    expect(source).toContain("fallbackRecent30m")
    expect(source).toContain("unexpected_real_credit_debits")
    expect(source).toContain("credit_transactions")
    expect(source).toContain("trial_credit_usages")
    expect(source).toContain("matchedExpectedFallbackReferences")
    expect(source).toContain("trial_billing_real_credit_fallback")
    expect(source).toContain("isExpectedTrialRealCreditFallbackEvent")
    expect(source).not.toContain("counts.trial_billing_real_credit_fallback > 50")
    expect(source).not.toMatch(/from\("user_credits"\)\s*\.update/)
    expect(source).not.toMatch(/from\("orders"\)\s*\.update/)
    expect(source).not.toMatch(/delete\(\)/)
  })
})
